name: Build and Deploy to VM

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/iotq/my-web:latest

    - name: Trigger Deployment Webhook
      run: |-
        curl -X POST \
          -H "X-Webhook-Token: ${{ secrets.WEBHOOK_TOKEN }}" \
          http://${{ secrets.VM_HOST }}:9000/hooks/deploy-my-web
